general:
  cpiApiServiceKeyCredentialsId: "cpi-test"
  integrationFlowId: "CICDTrial"
stages:
  uploadStage:
    enabled: true
  deployStage:
    enabled: true
  integrationTestStage:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "CICDTrial"
    integrationFlowName: "CICDTrial"
  integrationArtifactTriggerIntegrationTest:
    contentType: "application/json"
    messageBodyPath: ""
    iFlowServiceKeyCredentialsId: "cpi-test"
